apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-metrics-chart.fullname" . }}
  labels:
    {{- include "url-metrics-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "url-metrics-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "url-metrics-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: url-metrics-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
